- name: install and run ngnix
  hosts: web
  become: yes #equal to -b in adoc commands, getting root access
  tasks:
  - name: install ngnix
    ansible.builtin.dnf:
      name: ngnix
      state: latest
  - name: start ngnix
    ansible.builtin.service:
      name: ngnix
      state: started
      enabled: yes
