- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: Check user exist or not
    ansible.builtin.command: id expense1
    ignore_errors: true

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"
