- name: default values
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: "Hello {{Course | default('ansible') }}"
- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: conver into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: conver into lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  numbers: [1,1,2,3,4,5,6,7,7,8,8,8,9,9,10]
  tasks:
  - name: remove duplicate values from list
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"