- name: default values
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: "Hello {{Course | default('ansible') }}"
- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: conver into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: conver into lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,1,2,3,4,5,6,7,7,8,8,8,9,9,10]
  tasks:
  - name: remove duplicate values from list
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: min value from list
  hosts: localhost
  vars:
    numbers: [1,1,2,3,4,5,6,7,7,8,8,8,9,9,10]
  tasks:
  - name: Minimum values from list
    ansible.builtin.debug:
      msg: "{{ numbers | min }}"

- name: Max value from list
  hosts: localhost
  vars:
    numbers: [1,1,2,3,4,5,6,7,7,8,8,8,9,9,10]
  tasks:
  - name: Maximum values from list
    ansible.builtin.debug:
      msg: "{{ numbers | max }}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [25, 35, 67, 89]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: # this is called as dictionary or map or key/value pairs.
      Course: Ansbile
      Trainer: Sivakumar
      Duration: 120hr
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"