- name: default values
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: "Hello {{course | defalut('ansible') }}"
- name: upper case
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: conver into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"