- name: insatll packages
  hosts: web
  become: yes
  tasks:
  - name: insatll the packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - ngnix
    - postfix
